package com.sysone.eumaiwacs.common;

import lombok.Getter;

import java.util.HashMap;
import java.util.Map;

public enum AlarmType2Dept {
    PAGE_RESPONSE_TIME("Page Response Time", "tsPage", 1),
    PAGE_GAP_TIME("Page Gap Time", "tsPageGap", 2),
    PAGE_RESPONSE_INIT_TIME("Page Response Init Time", "tsPageResInit", 3),
    PAGE_RESPONSE_INIT_GAP_TIME("Page Response Init Gap Time", "tsPageResInitGap", 4),
    PAGE_RESPONSE_APP_TIME("Page Response App Time", "tsPageResApp", 5),
    PAGE_RESPONSE_APP_GAP_TIME("Page Response App Gap Time", "tsPageResAppGap", 6),
    PAGE_RESPONSE_RESPONSE_TIME("Page Response Response Time", "tsPageRes", 7),
    PAGE_RESPONSE_GAP_TIME("Page Response Gap Time", "tsPageResGap", 8),
    PAGE_TRANSFER_REQUEST_TIME("Page Transfer Request Time", "tsPageTransferReq", 9),
    PAGE_TRANSFER_REQUEST_GAP_TIME("Page Transfer Request Gap Time", "tsPageTransferReqGap", 10),
    PAGE_TRANSFER_RESPONSE_TIME("Page Transfer Response Time", "tsPageTransferRes", 11),
    PAGE_TRANSFER_RESPONSE_GAP_TIME("Page Transfer Response Gap Time", "tsPageTransferResGap", 12),
    PAGE_REQUEST_MAKING_TIME("Page Request Making Time", "tsPageReqMakingSum", 13),
    PAGE_REQUEST_MAKING_COUNT("Page Request Making Count", "pageReqMakingCnt", 14),
    PAGE_REQUEST_MAKING_MIN("Page Request Making Min", "tsPageReqMakingMin", 15),
    PAGE_REQUEST_MAKING_MAX("Page Request Making Max", "tsPageReqMakingMax", 16),
    STOPPED_TRANSACTION_COUNT("Stopped Transaction Count", "stoppedTransactionCnt", 17),
    PAGE_CONNECTION_RTT_REQ("Page Connection RTT (request)", "tsPageRttConnSumReq", 18),
    PAGE_CONNECTION_RTT_RES("Page Connection RTT (response)", "tsPageRttConnSumRes", 19),
    PAGE_CONNECTION_RTT_COUNT_REQ("Page Connection RTT Count (request)", "pageRttConnCntReq", 20),
    PAGE_CONNECTION_RTT_COUNT_RES("Page Connection RTT Count (response)", "pageRttConnCntRes", 21),
    PAGE_RTT_CONNECTION_MIN_REQ("Page RTT Connection Min (request)", "tsPageRttConnReqMin", 22),
    PAGE_RTT_CONNECTION_MIN_RES("Page RTT Connection Min (response)", "tsPageRttConnResMin", 23),
    PAGE_RTT_CONNECTION_MAX_REQ("Page RTT Connection Max (request)", "tsPageRttConnReqMax", 24),
    PAGE_RTT_CONNECTION_MAX_RES("Page RTT Connection Max (response)", "tsPageRttConnResMax", 25),
    PAGE_ACK_RTT_REQ("Page ACK RTT (request)", "tsPageRttAckSumReq", 26),
    PAGE_ACK_RTT_RES("Page ACK RTT (response)", "tsPageRttAckSumRes", 27),
    PAGE_ACK_RTT_COUNT_REQ("Page ACK RTT Count (request)", "pageRttAckCntReq", 28),
    PAGE_ACK_RTT_COUNT_RES("Page ACK RTT Count (response)", "pageRttAckCntRes", 29),
    PAGE_ACK_RTT_MIN_REQ("Page ACK RTT Min (request)", "tsPageRttAckReqMin", 30),
    PAGE_ACK_RTT_MIN_RES("Page ACK RTT Min (response)", "tsPageRttAckResMin", 31),
    PAGE_ACK_RTT_MAX_REQ("Page ACK RTT Max (request)", "tsPageRttAckReqMax", 32),
    PAGE_ACK_RTT_MAX_RES("Page ACK RTT Max (response)", "tsPageRttAckResMax", 33),
    PAGE_RTO_REQ("Page RTO (request)", "tsPageRtoSumReq", 34),
    PAGE_RTO_RES("Page RTO (response)", "tsPageRtoSumRes", 35),
    PAGE_RTO_COUNT_REQ("Page RTO Count (request)", "tsPageRtoCntReq", 36),
    PAGE_RTO_COUNT_RES("Page RTO Count (response)", "tsPageRtoCntRes", 37),
    HTTP_LENGTH_REQ("HTTP Length (request)", "pageHttpLenReq", 38),
    HTTP_LENGTH_RES("HTTP Length (response)", "pageHttpLenRes", 39),
    HTTP_COUNT_REQ("HTTP Count (request)", "pageHttpCntReq", 40),
    HTTP_COUNT_RES("HTTP Count (response)", "pageHttpCntRes", 41),
    PACKET_LENGTH_REQ("Packet Length (request)", "pagePktLenReq", 42),
    PACKET_LENGTH_RES("Packet Length (response)", "pagePktLenRes", 43),
    PACKET_COUNT_REQ("Packet Count (request)", "pagePktCntReq", 44),
    PACKET_COUNT_RES("Packet Count (response)", "pagePktCntRes", 45),
    CONNECTION_ERROR_PACKET_COUNT("Connection Error Packet Count", "connErrPktCnt", 46),
    SESSION_COUNT("Session Count", "pageSessionCnt", 47),
    CONNECTION_ERROR_SESSION_COUNT("Connection Error Session Count", "connErrSessionCnt", 48),
    CONNECTION_ERROR_SESSION_LENGTH_REQ("Connection Error Session Length (request)", "reqConnErrSessionLen", 49),
    CONNECTION_ERROR_SESSION_LENGTH_RES("Connection Error Session Length (response)", "resConnErrSessionLen", 50),
    TCP_LENGTH_REQ("TCP Length (request)", "pageTcpLenReq", 51),
    TCP_LENGTH_RES("TCP Length (response)", "pageTcpLenRes", 52),
    TCP_COUNT_REQ("TCP Count (request)", "pageTcpCntReq", 53),
    TCP_COUNT_RES("TCP Count (response)", "pageTcpCntRes", 54),
    RETRANSMISSION_COUNT_REQ("Retransmission Count (request)", "retransmissionCntReq", 55),
    RETRANSMISSION_COUNT_RES("Retransmission Count (response)", "retransmissionCntRes", 56),
    RETRANSMISSION_LENGTH_REQ("Retransmission Length (request)", "retransmissionLenReq", 57),
    RETRANSMISSION_LENGTH_RES("Retransmission Length (response)", "retransmissionLenRes", 58),
    FAST_RETRANSMISSION_COUNT_REQ("Fast Retransmission Count (request)", "fastRetransmissionCntReq", 59),
    FAST_RETRANSMISSION_COUNT_RES("Fast Retransmission Count (response)", "fastRetransmissionCntRes", 60),
    FAST_RETRANSMISSION_LENGTH_REQ("Fast Retransmission Length (request)", "fastRetransmissionLenReq", 61),
    FAST_RETRANSMISSION_LENGTH_RES("Fast Retransmission Length (response)", "fastRetransmissionLenRes", 62),
    OUT_OF_ORDER_COUNT_REQ("Out of Order Count (request)", "outOfOrderCntReq", 63),
    OUT_OF_ORDER_COUNT_RES("Out of Order Count (response)", "outOfOrderCntRes", 64),
    OUT_OF_ORDER_LENGTH_REQ("Out of Order Length (request)", "outOfOrderLenReq", 65),
    OUT_OF_ORDER_LENGTH_RES("Out of Order Length (response)", "outOfOrderLenRes", 66),
    LOST_SEGMENT_COUNT_REQ("Lost Segment Count (request)", "lostSegCntReq", 67),
    LOST_SEGMENT_COUNT_RES("Lost Segment Count (response)", "lostSegCntRes", 68),
    LOST_SEGMENT_LENGTH_REQ("Lost Segment Length (request)", "lostSegLenReq", 69),
    LOST_SEGMENT_LENGTH_RES("Lost Segment Length (response)", "lostSegLenRes", 70),
    ACK_LOST_COUNT_REQ("ACK Lost Count (request)", "ackLostCntReq", 71),
    ACK_LOST_COUNT_RES("ACK Lost Count (response)", "ackLostCntRes", 72),
    ACK_LOST_LENGTH_REQ("ACK Lost Length (request)", "ackLostLenReq", 73),
    ACK_LOST_LENGTH_RES("ACK Lost Length (response)", "ackLostLenRes", 74),
    DUP_ACK_COUNT_REQ("Dup ACK Count (request)", "dupAckCntReq", 75),
    DUP_ACK_COUNT_RES("Dup ACK Count (response)", "dupAckCntRes", 76),
    DUP_ACK_LENGTH_REQ("Dup ACK Length (request)", "dupAckLenReq", 77),
    DUP_ACK_LENGTH_RES("Dup ACK Length (response)", "dupAckLenRes", 78),
    ZERO_WINDOW_COUNT_REQ("Zero Window Count (request)", "zeroWinCntReq", 79),
    ZERO_WINDOW_COUNT_RES("Zero Window Count (response)", "zeroWinCntRes", 80),
    ZERO_WINDOW_LENGTH_REQ("Zero Window Length (request)", "zeroWinLenReq", 81),
    ZERO_WINDOW_LENGTH_RES("Zero Window Length (response)", "zeroWinLenRes", 82),
    SPURIOUS_RETRANSMISSION_COUNT_REQ("Spurious Retransmission Count (request)", "spuriousRetransmissionCntReq", 83),
    SPURIOUS_RETRANSMISSION_COUNT_RES("Spurious Retransmission Count (response)", "spuriousRetransmissionCntRes", 84),
    SPURIOUS_RETRANSMISSION_LENGTH_REQ("Spurious Retransmission Length (request)", "spuriousRetransmissionLenReq", 85),
    SPURIOUS_RETRANSMISSION_LENGTH_RES("Spurious Retransmission Length (response)", "spuriousRetransmissionLenRes", 86),
    OVERLAP_COUNT_REQ("Overlap Count (request)", "overlapCntReq", 87),
    OVERLAP_COUNT_RES("Overlap Count (response)", "overlapCntRes", 88),
    OVERLAP_LENGTH_REQ("Overlap Length (request)", "overlapLenReq", 89),
    OVERLAP_LENGTH_RES("Overlap Length (response)", "overlapLenRes", 90),
    OVERLAP_ATTACK_COUNT_REQ("Overlap Attack Count (request)", "overlapAttackCntReq", 91),
    OVERLAP_ATTACK_COUNT_RES("Overlap Attack Count (response)", "overlapAttackCntRes", 92),
    OVERLAP_ATTACK_LENGTH_REQ("Overlap Attack Length (request)", "overlapAttackLenReq", 93),
    OVERLAP_ATTACK_LENGTH_RES("Overlap Attack Length (response)", "overlapAttackLenRes", 94),
    ZERO_WINDOW_PROBE_COUNT_REQ("Zero Window Probe Count (request)", "zeroWinProbeCntReq", 95),
    ZERO_WINDOW_PROBE_COUNT_RES("Zero Window Probe Count (response)", "zeroWinProbeCntRes", 96),
    ZERO_WINDOW_PROBE_LENGTH_REQ("Zero Window Probe Length (request)", "zeroWinProbeLenReq", 97),
    ZERO_WINDOW_PROBE_LENGTH_RES("Zero Window Probe Length (response)", "zeroWinProbeLenRes", 98),
    ZERO_WINDOW_ACK_PROBE_COUNT_REQ("Zero Window ACK Probe Count (request)", "zeroWinProbeAckCntReq", 99),
    ZERO_WINDOW_ACK_PROBE_COUNT_RES("Zero Window ACK Probe Count (response)", "zeroWinProbeAckCntRes", 100),
    ZERO_WINDOW_ACK_PROBE_LENGTH_REQ("Zero Window ACK Probe Length (request)", "zeroWinProbeAckLenReq", 101),
    ZERO_WINDOW_ACK_PROBE_LENGTH_RES("Zero Window ACK Probe Length (response)", "zeroWinProbeAckLenRes", 102),
    KEEP_ALIVE_COUNT_REQ("Keep Alive Count (request)", "keepAliveCntReq", 103),
    KEEP_ALIVE_COUNT_RES("Keep Alive Count (response)", "keepAliveCntRes", 104),
    KEEP_ALIVE_LENGTH_REQ("Keep Alive Length (request)", "keepAliveLenReq", 105),
    KEEP_ALIVE_LENGTH_RES("Keep Alive Length (response)", "keepAliveLenRes", 106),
    KEEP_ALIVE_ACK_COUNT_REQ("Keep Alive ACK Count (request)", "keepAliveAckCntReq", 107),
    KEEP_ALIVE_ACK_COUNT_RES("Keep Alive ACK Count (response)", "keepAliveAckCntRes", 108),
    KEETP_ALIVE_ACK_LENGTH_REQ("Keep Alive ACK Length (request)", "keepAliveAckLenReq", 109),
    KEETP_ALIVE_ACK_LENGTH_RES("Keep Alive ACK Length (response)", "keepAliveAckLenRes", 110),
    WINDOW_UPDATE_COUNT_REQ("Window Update Count (request)", "winUpdateCntReq", 111),
    WINDOW_UPDATE_COUNT_RES("Window Update Count (response)", "winUpdateCntRes", 112),
    WINDOW_UPDATE_LENGTH_REQ("Window Update Length (request)", "winUpdateLenReq", 113),
    WINDOW_UPDATE_LENGTH_RES("Window Update Length (response)", "winUpdateLenRes", 114),
    CODE_2XX_COUNT("2xx Count", "resCode2xxCnt", 115),
    CODE_3XX_COUNT("3xx Count", "resCode3xxCnt", 116),
    CODE_401_COUNT("401 Count", "resCode401Cnt", 117),
    CODE_404_COUNT("404 Count", "resCode404Cnt", 118),
    CODE_4XX_COUNT("4xx Count", "resCode4xxCnt", 119),
    CODE_5XX_COUNT("5xx Count", "resCode5xxCnt", 120),
    CODE_OTHER_COUNT("Other Count", "resCodeOthCnt", 121),

    TS_REQ_DELAY_RESPONSE("Response Time", "tsRsqDelayResponse", 122),
    TS_REQ_DELAY_TRANSFER("Delay Transfer (request)", "tsReqDelayTransfer", 123),
    TS_RES_DELAY_TRANSFER("Delay Transfer (response)", "tsResDelayTransfer", 124),
    TS_RES_PROCESS_FIRST("Response Process First", "tsResProcessFirst", 125),
    TS_RES_PROCESS_PUSH("Response Process Push", "tsResProcessPush", 126),
    TS_RES_PROCESS_LAST("Response Process Last", "tsResProcessLast", 127),
    TS_FIRST_ACK_DELAY_REQ("First ACK Delay (request)", "tsFirstAckDelayReq", 128),
    TS_FIRST_ACK_DELAY_RES("First ACK Delay (response)", "tsFirstAckDelayRes", 129),
    TS_CONN_DELAY_REQ("Connection Delay (request)", "tsConnDelayReq", 130),
    TS_CONN_DELAY_RES("Connection Delay (response)", "tsConnDelayRes", 131),
    TS_REQ_MAKING("Request Making Time", "tsReqMaking", 132),
    ACK_DELAY_REQ("ACK Delay (request)", "ackDelayReq", 133),
    ACK_DELAY_RES("ACK Delay (response)", "ackDelayRes", 134),
    TS_RTT_SYN("RTT SYN", "tsRttSyn", 135),
    TS_RTT_SYN_ACK("RTT SYN ACK", "tsRttSynAck", 136),
    TS_RTT_FIRST_ACK("RTT First ACK", "tsRttFirstAck", 137),
    TS_RTT_REQ_ACK("RTT ACK (request)", "tsRttReqAck", 138),
    TS_RTT_RES_ACK("RTT ACK (response)", "tsRttResAck", 139),
    TS_RTT_ACK_REQ_ACK("RTT ACK Request ACK", "tsRttAckReqAck", 140),
    TS_RTT_ACK_RES_ACK("RTT ACK Response ACK", "tsRttAckResAck", 141),
    TS_RTT_FIRST_ACK_REQ("RTT First ACK (request)", "tsRttFirstAckReq", 142),
    TS_RTT_FIRST_ACK_RES("RTT First ACK (response)", "tsRttFirstAckRes", 143),
    TS_RTT_CONN_REQ("Connection RTT (request)", "tsRttConnReq", 144),
    TS_RTT_CONN_RES("Connection RTT (response)", "tsRttConnRes", 145),
    ACK_RTT_SUM_REQ("ACK RTT Sum (request)", "ackRttSumReq", 146),
    ACK_RTT_SUM_RES("ACK RTT Sum (response)", "ackRttSumRes", 147),
    ACK_RTT_CNT_REQ("ACK RTT Count (request)", "ackRttCntReq", 148),
    ACK_RTT_CNT_RES("ACK RTT Count (response)", "ackRttCntRes", 149),
    ACK_RTT_MIN_REQ("ACK RTT Min (request)", "ackRttMinReq", 150),
    ACK_RTT_MIN_RES("ACK RTT Min (response)", "ackRttMinRes", 151),
    ACK_RTT_MAX_REQ("ACK RTT Max (request)", "ackRttMaxReq", 152),
    ACK_RTT_MAX_RES("ACK RTT Max (response)", "ackRttMaxRes", 153),
    ACK_RTO_SUM_REQ("ACK RTO Sum (request)", "ackRtoSumReq", 154),
    ACK_RTO_SUM_RES("ACK RTO Sum (response)", "ackRtoSumRes", 155),
    ACK_RTO_CNT_REQ("ACK RTO Count (request)", "ackRtoCntReq", 156),
    ACK_RTO_CNT_RES("ACK RTO Count (response)", "ackRtoCntRes", 157),
    HTTP_LEN_REQ("HTTP Length (request)", "httpLenReq", 158),
    HTTP_LEN_RES("HTTP Length (response)", "httpLenRes", 159),
    HTTP_CNT_REQ("HTTP Count (request)", "httpCntReq", 160),
    HTTP_CNT_RES("HTTP Count (response)", "httpCntRes", 161),
    PKT_LEN_REQ("Packet Length (request)", "pktLenReq", 162),
    PKT_LEN_RES("Packet Length (response)", "pktLenRes", 163),
    PKT_CNT_REQ("Packet Count (request)", "pktCntReq", 164),
    PKT_CNT_RES("Packet Count (response)", "pktCntRes", 165),
    TCP_LEN_REQ("TCP Length (request)", "tcpLenReq", 166),
    TCP_LEN_RES("TCP Length (response)", "tcpLenRes", 167),
    TCP_CNT_REQ("TCP Count (request)", "tcpCntReq", 168),
    TCP_CNT_RES("TCP Count (response)", "tcpCntRes", 169),
    RETRANS_MISSION_CNT_REQ("Retransmission Count (request)", "retransmissionCntReq", 170),
    RETRANS_MISSION_CNT_RES("Retransmission Count (response)", "retransmissionCntRes", 171),
    RETRANS_MISSION_LEN_REQ("Retransmission Length (request)", "retransmissionLenReq", 172),
    RETRANS_MISSION_LEN_RES("Retransmission Length (response)", "retransmissionLenRes", 173),
    FAST_RETRANS_MISSION_CNT_REQ("Fast Retransmission Count (request)", "fastRetransmissionCntReq", 174),
    FAST_RETRANS_MISSION_CNT_RES("Fast Retransmission Count (response)", "fastRetransmissionCntRes", 175),
    FAST_RETRANS_MISSION_LEN_REQ("Fast Retransmission Length (request)", "fastRetransmissionLenReq", 176),
    FAST_RETRANS_MISSION_LEN_RES("Fast Retransmission Length (response)", "fastRetransmissionLenRes", 177),
    OUT_OF_ORDER_CNT_REQ("Out of Order Count (request)", "outOfOrderCntReq", 178),
    OUT_OF_ORDER_CNT_RES("Out of Order Count (response)", "outOfOrderCntRes", 179),
    OUT_OF_ORDER_LEN_REQ("Out of Order Length (request)", "outOfOrderLenReq", 180),
    OUT_OF_ORDER_LEN_RES("Out of Order Length (response)", "outOfOrderLenRes", 181),
    LOST_SEG_CNT_REQ("Lost Segment Count (request)", "lostSegCntReq", 182),
    LOST_SEG_CNT_RES("Lost Segment Count (response)", "lostSegCntRes", 183),
    LOST_SEG_LEN_REG("Lost Segment Length (request)", "lostSegLenReq", 184),
    LOST_SEG_LEN_RES("Lost Segment Length (response)", "lostSegLenRes", 185),
    ACK_LOST_CNT_REQ("ACK Lost Count (request)", "ackLostCntReq", 186),
    ACK_LOST_CNT_RES("ACK Lost Count (response)", "ackLostCntRes", 187),
    ACK_LOST_LEN_REQ("ACK Lost Length (request)", "ackLostLenReq", 188),
    ACK_LOST_LEN_RES("ACK Lost Length (response)", "ackLostLenRes", 189),
    DUP_ACK_CNT_REQ("Dup ACK Count (request)", "dupAckCntReq", 190),
    DUP_ACK_CNT_RES("Dup ACK Count (response)", "dupAckCntRes", 191),
    DUP_ACK_LEN_REQ("Dup ACK Length (request)", "dupAckLenReq", 192),
    DUP_ACK_LEN_RES("Dup ACK Length (response)", "dupAckLenRes", 193),
    ZERO_WIN_CNT_REQ("Zero Window Count (request)", "zeroWinCntReq", 194),
    ZERO_WIN_CNT_RES("Zero Window Count (response)", "zeroWinCntRes", 195),
    ZERO_WIN_LEN_REQ("Zero Window Length (request)", "zeroWinLenReq", 196),
    ZERO_WIN_LEN_RES("Zero Window Length (response)", "zeroWinLenRes", 197),
    SPURIOUS_RETRAMISSION_CNT_REQ("Spurious Retransmission Count (request)", "spuriousRetransmissionCntReq", 198),
    SPURIOUS_RETRAMISSION_CNT_RES("Spurious Retransmission Count (response)", "spuriousRetransmissionCntRes", 199),
    SPURIOUS_RETRAMISSION_LEN_REQ("Spurious Retransmission Length (request)", "spuriousRetransmissionLenReq", 200),
    SPURIOUS_RETRAMISSION_LEN_RES("Spurious Retransmission Length (response)", "spuriousRetransmissionLenRes", 201),
    OVERLAP_CNT_REQ("Overlap Count (request)", "overlapCntReq", 202),
    OVERLAP_CNT_RES("Overlap Count (response)", "overlapCntRes", 203),
    OVERLAP_LEN_REQ("Overlap Length (request)", "overlapLenReq", 204),
    OVERLAP_LEN_RES("Overlap Length (response)", "overlapLenRes", 205),
    OVERLAP_ATTACK_CNT_REQ("Overlap Attack Count (request)", "overlapAttackCntReq", 206),
    OVERLAP_ATTACK_CNT_RES("Overlap Attack Count (response)", "overlapAttackCntRes", 207),
    OVERLAP_ATTACK_LEN_REQ("Overlap Attack Length (request)", "overlapAttackLenReq", 208),
    OVERLAP_ATTACK_LEN_RES("Overlap Attack Length (response)", "overlapAttackLenRes", 209),
    ZERO_WIN_PRODE_CNT_REQ("Zero Window Probe Count (request)", "zeroWinProbeCntReq", 210),
    ZERO_WIN_PRODE_CNT_RES("Zero Window Probe Count (response)", "zeroWinProbeCntRes", 211),
    ZERO_WIN_PRODE_LEN_REQ("Zero Window Probe Length (request)", "zeroWinProbeLenReq", 212),
    ZERO_WIN_PRODE_LEN_RES("Zero Window Probe Length (response)", "zeroWinProbeLenRes", 213),
    ZERP_WIN_PROBE_ACK_CNT_REQ("Zero Window ACK Probe Count (request)", "zeroWinProbeAckCntReq", 214),
    ZERP_WIN_PROBE_ACK_CNT_RES("Zero Window ACK Probe Count (response)", "zeroWinProbeAckCntRes", 215),
    ZERO_WIN_PROBE_ACK_LEN_REQ("Zero Window ACK Probe Length (request)", "zeroWinProbeAckLenReq", 216),
    ZERO_WIN_PROBE_ACK_LEN_RES("Zero Window ACK Probe Length (response)", "zeroWinProbeAckLenRes", 217),
    KEEP_ALIVE_CNT_REQ("Keep Alive Count (request)", "keepAliveCntReq", 218),
    KEEP_ALIVE_CNT_RES("Keep Alive Count (response)", "keepAliveCntRes", 219),
    KEEP_ALIVE_LEN_REQ("Keep Alive Length (request)", "keepAliveLenReq", 220),
    KEEP_ALIVE_LEN_RES("Keep Alive Length (response)", "keepAliveLenRes", 221),
    KEEP_ALIVE_ACK_CNT_REQ("Keep Alive ACK Count (request)", "keepAliveAckCntReq", 222),
    KEEP_ALIVE_ACK_CNT_RES("Keep Alive ACK Count (response)", "keepAliveAckCntRes", 223),
    KEEP_ALIVE_ACK_LEN_REQ("Keep Alive ACK Length (request)", "keepAliveAckLenReq", 224),
    KEEP_ALIVE_ACK_LEN_RES("Keep Alive ACK Length (response)", "keepAliveAckLenRes", 225),
    WIN_UPDATE_CNT_REQ("Window Update Count (request)", "winUpdateCntReq", 226),
    WIN_UPDATE_CNT_RES("Window Update Count (response)", "winUpdateCntRes", 227),
    WIN_UPDATE_LEN_REQ("Window Update Length (request)", "winUpdateLenReq", 228),
    WIN_UPDATE_LEN_RES("Window Update Length (response)", "winUpdateLenRes", 229),

    TS_SYN("SYN", "tsSyn", 230),
    TS_SYN_ACK("SYN ACK", "tsSynAck", 231),
    TS_SYN_DELAY("SYN Delay", "tsSynDelay", 232),
    TS_SYN_ACK_DELAY("SYN ACK Delay", "tsSynackDelay", 233),
    TS_FIRST_ACK("First ACK", "tsFirstAck", 234),
    TS_FIRST_ACK_REQ("First ACK (request)", "tsFirstAckReq", 235),
    TS_FIRST_ACK_RES("First ACK (response)", "tsFirstAckRes", 236),
    TS_FIRST_ACK_REQ_ACK("First ACK Request ACK", "tsFirstAckReqAck", 237),
    TS_FIRST_ACK_RES_ACK("First ACK Response ACK", "tsFirstAckResAck", 238),
    TS_FIRST_PUSH_REQ("First Push (request)", "tsFirstPushReq", 239),
    TS_FIRST_PUSH_RES("First Push (response)", "tsFirstPushRes", 240),
    TS_ACK_DELAY_FIRST_REQ("ACK Delay First (request)", "tsAckDelayFirstReq", 241),
    TS_ACK_DELAY_FIRST_RES("ACK Delay First (response)", "tsAckDelayFirstRes", 242),
    TS_ACK_DELAY_LAST_REQ("ACK Delay Last (request)", "tsAckDelayLastReq", 243),
    TS_ACK_DELAY_LAST_RES("ACK Delay Last (response)", "tsAckDelayLastRes", 244),
    STPPPED_TRANSACTION("Stopped Transaction", "stoppedTransaction", 245),
    LEN_PDU_REQ_TOT("Length PDU Total (request)", "lenPduReqTot", 246),
    LEN_PDU_RES_TOT("Length PDU Total (response)", "lenPduResTot", 237),
    LEN_PDU_REQ_PER_SEC("Length PDU Per Sec (request)", "lenPduReqPerSec", 238),
    LEN_PDU_RES_PER_SEC("Length PDU Per Sec (response)", "lenPduResPerSec", 239),
    LEN_PDU_REQ_DELTA("Length PDU Delta (request)", "lenPduReqDelta", 240),
    LEN_PDU_RES_DELTA("Length PDU Delta (response)", "lenPduResDelta", 241),
    PKTS_PDU_REQ_TOT("Packets PDU Total (request)", "pktsPduReqTot", 242),
    PKTS_PDU_RES_TOT("Packets PDU Total (response)", "pktsPduResTot", 243),
    PKTS_PDU_REQ_PER_SEC("Packets PDU Per Sec (request)", "pktsPduReqPerSec", 244),
    PKTS_PDU_RES_PER_SEC("Packets PDU Per Sec (response)", "pktsPduResPerSec", 245),
    PKTS_PDU_REQ_DELTA("Packets PDU Delta (request)", "pktsPduReqDelta", 246),
    PKTS_PDU_RES_DELTA("Packets PDU Delta (response)", "pktsPduResDelta", 247),
    TS_RTT_LAST_ACK_REQ("RTT Last ACK (request)", "tsRttLastAckReq", 248),
    TS_RTT_LAST_ACK_RES("RTT Last ACK (response)", "tsRttLastAckRes", 249),
    ACL_RTT_CNT_RES("ACK RTT Count (response)", "ackRttCntRes", 250),
    ACK_RTT_MIN_REQ_TOT("ACK RTT Min Total (request)", "ackRttMinReqTot", 251),
    ACK_RTT_MIN_RES_TOT("ACK RTT Min Total (response)", "ackRttMinResTot", 252),
    ACK_RTT_MAX_REQ_TOT("ACK RTT Max Total (request)", "ackRttMaxReqTot", 253),
    ACK_RTT_MAX_RES_TOT("ACK RTT Max Total (response)", "ackRttMaxResTot", 254),
    ACK_RTT_MIN_REQ_CURR("ACK RTT Min Current (request)", "ackRttMinReqCurr", 255),
    ACK_RTT_MIN_RES_CURR("ACK RTT Min Current (response)", "ackRttMinResCurr", 256),
    ACK_RTT_MAX_REQ_CURR("ACK RTT Max Current (request)", "ackRttMaxReqCurr", 257),
    ACK_RTT_MAX_RES_CURR("ACK RTT Max Current (response)", "ackRttMaxResCurr", 258),
    RETRANSMISSION_CNT_REQ_TOT("Retransmission Count (request)", "retransmissionCntReqTot", 259),
    RETRANSMISSION_CNT_RES_TOT("Retransmission Count (response)", "retransmissionCntResTot", 260),
    RETRANSMISSION_LEN_REQ_TOT("Retransmission Length (request)", "retransmissionLenReqTot", 261),
    RETRANSMISSION_LEN_RES_TOT("Retransmission Length (response)", "retransmissionLenResTot", 262),
    FAST_RETRANSMISSION_CNT_REQ_TOT("Fast Retransmission Count (request)", "fastretransmissionCntReqTot", 263),
    FAST_RETRANSMISSION_CNT_RES_TOT("Fast Retransmission Count (response)", "fastretransmissionCntResTot", 264),
    FAST_RETRANSMISSION_LEN_REQ_TOT("Fast Retransmission Length (request)", "fastretransmissionLenReqTot", 265),
    FAST_RETRANSMISSION_LEN_RES_TOT("Fast Retransmission Length (response)", "fastretransmissionLenResTot", 266),
    OUT_OF_ORDER_CNT_REQ_TOT("Out of Order Count (request)", "outoforderCntReqTot", 267),
    OUT_OF_ORDER_CNT_RES_TOT("Out of Order Count (response)", "outoforderCntResTot", 268),
    OUT_OF_ORDER_LEN_REQ_TOT("Out of Order Length (request)", "outoforderLenReqTot", 269),
    OUT_OF_ORDER_LEN_RES_TOT("Out of Order Length (response)", "outoforderLenResTot", 270),
    LOST_SEG_CNT_REQ_TOT("Lost Segment Count (request)", "lostsegCntReqTot", 271),
    LOST_SEG_CNT_RES_TOT("Lost Segment Count (response)", "lostsegCntResTot", 272),
    LOST_SEG_LEN_REQ_TOT("Lost Segment Length (request)", "lostsegLenReqTot", 273),
    LOST_SEG_LEN_RES_TOT("Lost Segment Length (response)", "lostsegLenResTot", 274),
    ACK_LOAT_CNT_REQ_TOT("ACK Lost Count (request)", "acklostCntReqTot", 275),
    ACK_LOST_CNT_RES_TOT("ACK Lost Count (response)", "acklostCntResTot", 276),
    ACK_LOST_LEN_REQ_TOT("ACK Lost Length (request)", "acklostLenReqTot", 277),
    ACK_LOST_LEN_RES_TOT("ACK Lost Length (response)", "acklostLenResTot", 278),
    DUP_ACK_CNT_REQ_TOT("Dup ACK Count (request)", "dupackCntReqTot", 279),
    DUP_ACK_CNT_RES_TOT("Dup ACK Count (response)", "dupackCntResTot", 280),
    DUP_ACK_LEN_REQ_TOT("Dup ACK Length (request)", "dupackLenReqTot", 281),
    DUP_ACK_LEN_RES_TOT("Dup ACK Length (response)", "dupackLenResTot", 282),
    ZERO_WIN_CNT_REQ_TOT("Zero Window Count (request)", "zerowinCntReqTot", 283),
    ZERO_WIN_CNT_RES_TOT("Zero Window Count (response)", "zerowinCntResTot", 284),
    ZERO_WIN_LEN_REQ_TOT("Zero Window Length (request)", "zerowinLenReqTot", 285),
    ZERO_WIN_LEN_RES_TOT("Zero Window Length (response)", "zerowinLenResTot", 286),
    SPURIOUS_RETRANSMISSION_CNT_REQ_TOT("Spurious Retransmission Count (request)", "spuriousRetransmissionCntReqTot", 287),
    SPURIOUS_RETRANSMISSION_CNT_RES_TOT("Spurious Retransmission Count (response)", "spuriousRetransmissionCntResTot", 288),
    SPURIOUS_RETRANMISSION_LEN_REQ_TOT("Spurious Retransmission Length (request)", "spuriousRetransmissionLenReqTot", 289),
    SPURIOUS_RETRANMISSION_LEN_RES_TOT("Spurious Retransmission Length (response)", "spuriousRetransmissionLenResTot", 290),
    OVERLAP_CNT_REQ_TOT("Overlap Count (request)", "overlapCntReqTot", 291),
    OVERLAP_CNT_RES_TOT("Overlap Count (response)", "overlapCntResTot", 292),
    OVERLAP_LEN_REQ_TOT("Overlap Length (request)", "overlapLenReqTot", 293),
    OVERLAP_LEN_RES_TOT("Overlap Length (response)", "overlapLenResTot", 294),
    OVERLAP_ATTACK_CNT_REQ_TOT("Overlap Attack Count (request)", "overlapAttackCntReqTot", 295),
    OVERLAP_ATTACK_CNT_RES_TOT("Overlap Attack Count (response)", "overlapAttackCntResTot", 296),
    OVERLAP_ATTACK_LEN_REQ_TOT("Overlap Attack Length (request)", "overlapAttackLenReqTot", 297),
    OVERLAP_ATTACK_LEN_RES_TOT("Overlap Attack Length (response)", "overlapAttackLenResTot", 298),
    ZERO_WIN_PROBE_CNT_REQ_TOT("Zero Window Probe Count (request)", "zeroWinProbeCntReqTot", 299),
    ZERO_WIN_PROBE_CNT_RES_TOT("Zero Window Probe Count (response)", "zeroWinProbeCntResTot", 300),
    ZERO_WIN_PROBE_LEN_REQ_TOT("Zero Window Probe Length (request)", "zeroWinProbeLenReqTot", 301),
    ZERO_WIN_PROBE_LEN_RES_TOT("Zero Window Probe Length (response)", "zeroWinProbeLenResTot", 302),
    ZERO_WIN_PROBE_ACK_CNT_REQ_TOT("Zero Window ACK Probe Count (request)", "zeroWinProbeAckCntReqTot", 303),
    ZERO_WIN_PROBE_ACK_CNT_RES_TOT("Zero Window ACK Probe Count (response)", "zeroWinProbeAckCntResTot", 304),
    ZERO_WIN_PROBE_ACK_LEN_REQ_TOT("Zero Window ACK Probe Length (request)", "zeroWinProbeAckLenReqTot", 305),
    ZERO_WIN_PROBE_ACK_LEN_RES_TOT("Zero Window ACK Probe Length (response)", "zeroWinProbeAckLenResTot", 306),
    KEEP_ALIVE_CNT_REQ_TOT("Keep Alive Count (request)", "keepAliveCntReqTot", 307),
    KEEP_ALIVE_CNT_RES_TOT("Keep Alive Count (response)", "keepAliveCntResTot", 308),
    KEEP_ALIVE_LEN_REQ_TOT("Keep Alive Length (request)", "keepAliveLenReqTot", 309),
    KEEP_ALIVE_LEN_RES_TOT("Keep Alive Length (response)", "keepAliveLenResTot", 310),
    KEEP_ALIVE_ACK_CNT_REQ_TOT("Keep Alive ACK Count (request)", "keepAliveAckCntReqTot", 311),
    KEEP_ALIVE_ACK_CNT_RES_TOT("Keep Alive ACK Count (response)", "keepAliveAckCntResTot", 312),
    KEEP_ALIVE_ACK_LEN_REQ_TOT("Keep Alive ACK Length (request)", "keepAliveAckLenReqTot", 313),
    KEEP_ALIVE_ACK_LEN_RES_TOT("Keep Alive ACK Length (response)", "keepAliveAckLenResTot", 314),
    WIN_UPDATE_CNT_REQ_TOT("Window Update Count (request)", "winupdateCntReqTot", 315),
    WIN_UPDATE_CNT_RES_TOT("Window Update Count (response)", "winupdateCntResTot", 316),
    WIN_UPDATE_LEN_REQ_TOT("Window Update Length (request)", "winupdateLenReqTot", 317),
    WIN_UPDATE_LEN_RES_TOT("Window Update Length (response)", "winupdateLenResTot", 318),
    RETRANSMISSTION_CNT_REQ_PER_SEC("Retransmission Count (request)", "retransmissionCntReqPerSec", 319),
    RETRANSMISSTION_CNT_RES_PER_SEC("Retransmission Count (response)", "retransmissionCntResPerSec", 320),
    RETRANSMISSTION_LEN_REQ_PER_SEC("Retransmission Length (request)", "retransmissionLenReqPerSec", 321),
    RETRANSMISSTION_LEN_RES_PER_SEC("Retransmission Length (response)", "retransmissionLenResPerSec", 322),
    FAST_RETRANSMISSION_CNT_REQ_PER_SEC("Fast Retransmission Count (request)", "fastretransmissionCntReqPerSec", 323),
    FAST_RETRANMISSION_LEN_REQ_PER_SEC("Fast Retransmission Length (request)", "fastretransmissionLenReqPerSec", 324),
    FAST_RETRANMISSION_LEN_RES_PER_SEC("Fast Retransmission Length (response)", "fastretransmissionLenResPerSec", 325),
    OUT_OF_ORDER_CNT_REQ_PER_SEC("Out of Order Count (request)", "outoforderCntReqPerSec", 326),
    OUT_OF_ORDER_CNT_RES_PER_SEC("Out of Order Count (response)", "outoforderCntResPerSec", 327),
    OUT_OF_ORDER_LEN_REQ_PER_SEC("Out of Order Length (request)", "outoforderLenReqPerSec", 328),
    OUT_OF_ORDER_LEN_RES_PER_SEC("Out of Order Length (response)", "outoforderLenResPerSec", 329),
    LOST_SEG_CNT_REQ_PER_SEC("Lost Segment Count (request)", "lostsegCntReqPerSec", 330),
    LOST_SEG_CNT_RES_PER_SEC("Lost Segment Count (response)", "lostsegCntResPerSec", 331),
    LOST_SEG_LEN_REQ_PER_SEC("Lost Segment Length (request)", "lostsegLenReqPerSec", 332),
    LOST_SEG_LEN_RES_PER_SEC("Lost Segment Length (response)", "lostsegLenResPerSec", 333),
    ACK_LOST_CNT_REQ_PER_SEC("ACK Lost Count (request)", "acklostCntReqPerSec", 334),
    ACK_LOST_CNT_RES_PER_SEC("ACK Lost Count (response)", "acklostCntResPerSec", 335),
    ACK_LOST_LEN_REQ_PER_SEC("ACK Lost Length (request)", "acklostLenReqPerSec", 336),
    ACK_LOST_LEN_RES_PER_SEC("ACK Lost Length (response)", "acklostLenResPerSec", 337),
    DUP_ACK_CNT_REQ_PER_SEC("Dup ACK Count (request)", "dupackCntReqPerSec", 338),
    DUP_ACK_CNT_RES_PER_SEC("Dup ACK Count (response)", "dupackCntResPerSec", 339),
    DUP_ACK_LEN_REQ_PER_SEC("Dup ACK Length (request)", "dupackLenReqPerSec", 340),
    DUP_ACK_LEN_RES_PER_SEC("Dup ACK Length (response)", "dupackLenResPerSec", 341),
    ZERO_WIN_CNT_REQ_PER_SEC("Zero Window Count (request)", "zerowinCntReqPerSec", 342),
    ZERO_WIN_CNT_RES_PER_SEC("Zero Window Count (response)", "zerowinCntResPerSec", 343),
    ZERO_WIN_LEN_REQ_PER_SEC("Zero Window Length (request)", "zerowinLenReqPerSec", 344),
    ZERO_WIN_LEN_RES_PER_SEC("Zero Window Length (response)", "zerowinLenResPerSec", 345),
    SPURIOUS_RETRANSMISSION_CNT_REQ_PER_SEC("Spurious Retransmission Count (request)", "spuriousRetransmissionCntReqPerSec", 346),
    SPURIOUS_RETRANSMISSION_CNT_RES_PER_SEC("Spurious Retransmission Count (response)", "spuriousRetransmissionCntResPerSec", 347),
    SPURIOUS_RETRANSMISSION_LEN_REQ_PER_SEC("Spurious Retransmission Length (request)", "spuriousRetransmissionLenReqPerSec", 348),
    SPURIOUS_RETRANSMISSION_LEN_RES_PER_SEC("Spurious Retransmission Length (response)", "spuriousRetransmissionLenResPerSec", 349),
    OVERLAP_CNT_REQ_PER_SEC("Overlap Count (request)", "overlapCntReqPerSec", 350),
    OVERLAP_CNT_RES_PER_SEC("Overlap Count (response)", "overlapCntResPerSec", 351),
    OVERLAP_LEN_REQ_PER_SEC("Overlap Length (request)", "overlapLenReqPerSec", 352),
    OVERLAP_LEN_RES_PER_SEC("Overlap Length (response)", "overlapLenResPerSec", 353),
    OVERLAP_ATTACK_CNT_REQ_PER_SEC("Overlap Attack Count (request)", "overlapAttackCntReqPerSec", 354),
    OVERLAP_ATTACK_CNT_RES_PER_SEC("Overlap Attack Count (response)", "overlapAttackCntResPerSec", 355),
    OVERLAP_ATTACK_LEN_REQ_PER_SEC("Overlap Attack Length (request)", "overlapAttackLenReqPerSec", 356),
    OVERLAP_ATTACK_LEN_RES_PER_SEC("Overlap Attack Length (response)", "overlapAttackLenResPerSec", 357),
    ZERO_WIN_PROBE_CNT_REQ_PER_SEC("Zero Window Probe Count (request)", "zeroWinProbeCntReqPerSec", 358),
    ZERO_WIN_PROBE_CNT_RES_PER_SEC("Zero Window Probe Count (response)", "zeroWinProbeCntResPerSec", 359),
    ZERO_WIN_PROBE_LEN_REQ_PER_SEC("Zero Window Probe Length (request)", "zeroWinProbeLenReqPerSec", 360),
    ZERO_WIN_PROBE_LEN_RES_PER_SEC("Zero Window Probe Length (response)", "zeroWinProbeLenResPerSec", 361),
    ZERO_WIN_PROBE_ACK_CNT_REQ_PER_SEC("Zero Window ACK Probe Count (request)", "zeroWinProbeAckCntReqPerSec", 362),
    ZERO_WIN_PROBE_ACK_CNT_RES_PER_SEC("Zero Window ACK Probe Count (response)", "zeroWinProbeAckCntResPerSec", 363),
    ZER0_WIN_PROBE_ACK_LEN_REQ_PER_SEC("Zero Window ACK Probe Length (request)", "zeroWinProbeAckLenReqPerSec", 364),
    ZERO_WIN_PROBE_ACK_LEN_RES_PER_SEC("Zero Window ACK Probe Length (response)", "zeroWinProbeAckLenResPerSec", 365),
    KEEP_ALIVE_CNT_REQ_PER_SEC("Keep Alive Count (request)", "keepAliveCntReqPerSec", 366),
    KEEP_ALIVE_CNT_RES_PER_SEC("Keep Alive Count (response)", "keepAliveCntResPerSec", 367),
    KEEP_ALIVE_LEN_REQ_PER_SEC("Keep Alive Length (request)", "keepAliveLenReqPerSec", 368),
    KEEP_ALIVE_LEN_RES_PER_SEC("Keep Alive Length (response)", "keepAliveLenResPerSec", 369),
    KEEP_ALIVE_ACK_CNT_REQ_PER_SEC("Keep Alive ACK Count (request)", "keepAliveAckCntReqPerSec", 370),
    KEEP_ALIVE_ACK_CNT_RES_PER_SEC("Keep Alive ACK Count (response)", "keepAliveAckCntResPerSec", 371),
    KEEP_ALIVE_ACK_LEN_REQ_PER_SEC("Keep Alive ACK Length (request)", "keepAliveAckLenReqPerSec", 372),
    KEEP_ALIVE_ACK_LEN_RES_PER_SEC("Keep Alive ACK Length (response)", "keepAliveAckLenResPerSec", 373),
    WIN_UPDATE_CNT_REQ_PER_SEC("Window Update Count (request)", "winupdateCntReqPerSec", 374),
    WIN_UPDATE_CNT_RES_PER_SEC("Window Update Count (response)", "winupdateCntResPerSec", 375),
    WIN_UPDATE_LEN_REQ_PER_SEC("Window Update Length (request)", "winupdateLenReqPerSec", 376),
    WIN_UPDATE_LEN_RES_PER_SEC("Window Update Length (response)", "winupdateLenResPerSec", 377),
    RETRANSMISSION_CNT_REQ_DELTA("Retransmission Count (request)", "retransmissionCntReqDelta", 378),
    RETRANSMISSION_CNT_RES_DELTA("Retransmission Count (response)", "retransmissionCntResDelta", 379),
    RETRANSMISSION_LEN_REQ_DELTA("Retransmission Length (request)", "retransmissionLenReqDelta", 380),
    RETRANSMISSION_LEN_RES_DELTA("Retransmission Length (response)", "retransmissionLenResDelta", 381),
    RAST_RETRANSMISSION_CNT_REQ_DELTA("Fast Retransmission Count (request)", "fastretransmissionCntReqDelta", 382),
    FAST_RETRANSMISSION_CNT_RES_DELTA("Fast Retransmission Count (response)", "fastretransmissionCntResDelta", 383),
    FAST_RETRANSMISSION_LEN_REQ_DELTA("Fast Retransmission Length (request)", "fastretransmissionLenReqDelta", 384),
    FAST_RETRANSMISSION_LEN_RES_DELAT("Fast Retransmission Length (response)", "fastretransmissionLenResDelta", 385),
    OUT_OF_ORDER_CNT_REQ_DELTA("Out of Order Count (request)", "outoforderCntReqDelta", 386),
    OUT_OF_ORDER_CNT_RES_DELTA("Out of Order Count (response)", "outoforderCntResDelta", 387),
    OUT_OF_ORDER_LEN_REQ_DELTA("Out of Order Length (request)", "outoforderLenReqDelta", 388),
    OUT_OF_ORDER_LEN_RES_DELTA("Out of Order Length (response)", "outoforderLenResDelta", 389),
    LOST_SEG_CNT_REQ_DELTA("Lost Segment Count (request)", "lostsegCntReqDelta", 390),
    LOST_SEG_CNT_RES_DELTA("Lost Segment Count (response)", "lostsegCntResDelta", 391),
    LOST_SEG_LEN_REQ_DELTA("Lost Segment Length (request)", "lostsegLenReqDelta", 392),
    LOST_SEG_LEN_RES_DELTA("Lost Segment Length (response)", "lostsegLenResDelta", 393),
    ACK_LOST_CNT_REQ_DELTA("ACK Lost Count (request)", "acklostCntReqDelta", 394),
    ACK_LOST_CNT_RES_DELTA("ACK Lost Count (response)", "acklostCntResDelta", 395),
    ACK_LOST_LEN_REG_DELTA("ACK Lost Length (request)", "acklostLenReqDelta", 396),
    ACK_LOST_LEN_RES_DELTA("ACK Lost Length (response)", "acklostLenResDelta", 397),
    DUP_ACK_CNT_REQ_DELTA("Dup ACK Count (request)", "dupackCntReqDelta", 398),
    DUP_ACK_CNT_RES_DELTA("Dup ACK Count (response)", "dupackCntResDelta", 399),
    DUP_ACK_LEN_REQ_DELTA("Dup ACK Length (request)", "dupackLenReqDelta", 400),
    ZERO_WIN_CNT_REQ_DELTA("Zero Window Count (request)", "zerowinCntReqDelta", 401),
    ZERO_WIN_CNT_RES_DELTA("Zero Window Count (response)", "zerowinCntResDelta", 402),
    ZERO_WIN_LEN_REQ_DELTA("Zero Window Length (request)", "zerowinLenReqDelta", 403),
    ZERO_WIN_LEN_RES_DELTA("Zero Window Length (response)", "zerowinLenResDelta", 404),
    SPURIOUS_RETRANSMISSION_CNT_REQ_DELTA("Spurious Retransmission Count (request)", "spuriousRetransmissionCntReqDelta", 405),
    SPURIOUS_RETRANSMISSION_CNT_RES_DELTA("Spurious Retransmission Count (response)", "spuriousRetransmissionCntResDelta", 406),
    SPURIOUS_RETRANMISSION_REQ_DELTA("Spurious Retransmission Length (request)", "spuriousRetransmissionLenReqDelta", 407),
    SPURIOUS_RETRANMISSION_RES_DELTA("Spurious Retransmission Length (response)", "spuriousRetransmissionLenResDelta", 408),
    OVERLAP_CNT_REQ_DELTA("Overlap Count (request)", "overlapCntReqDelta", 409),
    OVERLAP_CNT_RES_DELTA("Overlap Count (response)", "overlapCntResDelta", 410),
    OVERLAP_LEN_REQ_DELTA("Overlap Length (request)", "overlapLenReqDelta", 411),
    OVERLAP_LEN_RES_DELTA("Overlap Length (response)", "overlapLenResDelta", 412),
    OVERLAP_ATTACK_CNT_REQ_DELTA("Overlap Attack Count (request)", "overlapAttackCntReqDelta", 413),
    OVERLAP_ATTACK_CNT_RES_DELTA("Overlap Attack Count (response)", "overlapAttackCntResDelta", 414),
    OVERLAP_ATTACK_LEN_REQ_DELTA("Overlap Attack Length (request)", "overlapAttackLenReqDelta", 415),
    OVERLAP_ATTACK_LEN_RES_DELTA("Overlap Attack Length (response)", "overlapAttackLenResDelta", 416),
    ZERO_WIN_PROBE_CNT_REQ_DELTA("Zero Window Probe Count (request)", "zeroWinProbeCntReqDelta", 417),
    ZERO_WIN_PROBE_CNT_RES_DELTA("Zero Window Probe Count (response)", "zeroWinProbeCntResDelta", 418),
    ZERO_WIN_PROBE_LEN_REQ_DELTA("Zero Window Probe Length (request)", "zeroWinProbeLenReqDelta", 419),
    ZERO_WIN_PROBE_LEN_RES_DELTA("Zero Window Probe Length (response)", "zeroWinProbeLenResDelta", 420),
    ZERO_WIN_PROBE_ACK_CNT_REQ_DELTA("Zero Window ACK Probe Count (request)", "zeroWinProbeAckCntReqDelta", 421),
    ZERO_WIN_PROBE_ACK_CNT_RES_DELTA("Zero Window ACK Probe Count (response)", "zeroWinProbeAckCntResDelta", 422),
    ZERO_WIN_PROBE_ACK_LEN_REQ_DELTA("Zero Window ACK Probe Length (request)", "zeroWinProbeAckLenReqDelta", 423),
    ZERO_WIN_PROBE_ACK_LEN_RES_DELTA("Zero Window ACK Probe Length (response)", "zeroWinProbeAckLenResDelta", 424),
    KEEP_ALIVE_CNT_REQ_DELTA("Keep Alive Count (request)", "keepAliveCntReqDelta", 425),
    KEEP_ALIVE_CNT_RES_DELTA("Keep Alive Count (response)", "keepAliveCntResDelta", 426),
    KEEP_ALIVE_LEN_REQ_DELTA("Keep Alive Length (request)", "keepAliveLenReqDelta", 427),
    KEEP_ALIVE_LEN_RES_DELTA("Keep Alive Length (response)", "keepAliveLenResDelta", 428),
    KEEP_ALIVE_ACK_CNT_REQ_DELTA("Keep Alive ACK Count (request)", "keepAliveAckCntReqDelta", 429),
    KEEP_ALIVE_ACK_CNT_RES_DELTA("Keep Alive ACK Count (response)", "keepAliveAckCntResDelta", 430),
    KEEP_ALIVE_ACK_LEN_REQ_DELTA("Keep Alive ACK Length (request)", "keepAliveAckLenReqDelta", 431),
    KEEP_ALIVE_ACK_LEN_RES_DELTA("Keep Alive ACK Length (response)", "keepAliveAckLenResDelta", 432),
    WIN_UPDATE_CNT_REQ_DELTA("Window Update Count (request)", "winupdateCntReqDelta", 433),
    WIN_UPDATE_CNT_RES_DELTA("Window Update Count (response)", "winupdateCntResDelta", 434),
    WIN_UPDATE_LEN_REQ_DELTA("Window Update Length (request)", "winupdateLenReqDelta", 435),
    WIN_UPDATE_LEN_RES_DELTA("Window Update Length (response)", "winupdateLenResDelta", 436),
    TCP_FLAG_STAT_FIN_REQ_TOT("TCP Flag Stat Fin (request)", "tcpFlagStatFinReqTot", 437),
    TCP_FLAG_STAT_FIN_RES_TOT("TCP Flag Stat Fin (response)", "tcpFlagStatFinResTot", 438),
    TCP_FLAG_STAT_SYN_REQ_TOT("TCP Flag Stat SYN (request)", "tcpFlagStatSynReqTot", 439),
    TCP_FLAG_STAT_SYN_RES_TOT("TCP Flag Stat SYN (response)", "tcpFlagStatSynResTot", 440),
    TCP_FLAG_STAT_RST_REQ_TOT("TCP Flag Stat Rst (request)", "tcpFlagStatRstReqTot", 441),
    TCP_FLAG_STAT_RST_RES_TOT("TCP Flag Stat Rst (response)", "tcpFlagStatRstResTot", 442),
    TCP_FLAG_STAT_PSH_REQ_TOT("TCP Flag Stat Psh (request)", "tcpFlagStatPshReqTot", 443),
    TCP_FLAG_STAT_PSH_RES_TOT("TCP Flag Stat Psh (response)", "tcpFlagStatPshResTot", 444),
    TCP_FLAG_STAT_ACK_REQ_TOT("TCP Flag Stat ACK (request)", "tcpFlagStatAckReqTot", 445),
    TCP_FLAG_STAT_ACK_RES_TOT("TCP Flag Stat ACK (response)", "tcpFlagStatAckResTot", 446),
    TCP_FLAG_STAT_URG_REQ_TOT("TCP Flag Stat Urg (request)", "tcpFlagStatUrgReqTot", 447),
    TCP_FLAG_STAT_URG_RES_TOT("TCP Flag Stat Urg (response)", "tcpFlagStatUrgResTot", 448),
    TCP_FLAG_STAT_FIN_REQ_PER_SEC("TCP Flag Stat Fin (request)", "tcpFlagStatFinReqPerSec", 449),
    TCP_FLAG_STAT_FIN_RES_PER_SEC("TCP Flag Stat Fin (response)", "tcpFlagStatFinResPerSec", 450),
    TCP_FLAG_STAT_SYN_REQ_PER_SEC("TCP Flag Stat SYN (request)", "tcpFlagStatSynReqPerSec", 451),
    TCP_FLAG_STAT_SYN_RES_PER_SEC("TCP Flag Stat SYN (response)", "tcpFlagStatSynResPerSec", 452),
    TCP_FLAG_STAT_RST_REQ_PER_SEC("TCP Flag Stat Rst (request)", "tcpFlagStatRstReqPerSec", 453),
    TCP_FLAG_STAT_RST_RES_PER_SEC("TCP Flag Stat Rst (response)", "tcpFlagStatRstResPerSec", 454),
    TCP_FLAG_STAT_PSH_REQ_PER_SEC("TCP Flag Stat Psh (request)", "tcpFlagStatPshReqPerSec", 455),
    TCP_FLAG_STAT_PSH_RES_PER_SEC("TCP Flag Stat Psh (response)", "tcpFlagStatPshResPerSec", 456),
    TCP_FLAG_STAT_ACK_REQ_PER_SEC("TCP Flag Stat ACK (request)", "tcpFlagStatAckReqPerSec", 457),
    TCP_FLAG_STAT_ACK_RES_PER_SEC("TCP Flag Stat ACK (response)", "tcpFlagStatAckResPerSec", 458),
    TCP_FLAG_STAT_URG_REQ_PER_SEC("TCP Flag Stat Urg (request)", "tcpFlagStatUrgReqPerSec", 459),
    TCP_FLAG_STAT_URG_RES_PER_SEC("TCP Flag Stat Urg (response)", "tcpFlagStatUrgResPerSec", 460),
    TCP_FLAG_STAT_FIN_REQ_DELTA("TCP Flag Stat Fin (request)", "tcpFlagStatFinReqDelta", 461),
    TCP_FLAG_STAT_FIN_RES_DELTA("TCP Flag Stat Fin (response)", "tcpFlagStatFinResDelta", 462),
    TCP_FLAG_STAT_SYN_REQ_DELTA("TCP Flag Stat SYN (request)", "tcpFlagStatSynReqDelta", 463),
    TCP_FLAG_STAT_SYN_RES_DELTA("TCP Flag Stat SYN (response)", "tcpFlagStatSynResDelta", 464),
    TCP_FLAG_STAT_RST_REQ_DELTA("TCP Flag Stat Rst (request)", "tcpFlagStatRstReqDelta", 465),
    TCP_FLAG_STAT_RST_RES_DELTA("TCP Flag Stat Rst (response)", "tcpFlagStatRstResDelta", 466),
    TCP_FLAG_STAT_PSH_REQ_DELTA("TCP Flag Stat Psh (request)", "tcpFlagStatPshReqDelta", 467),
    TCP_FLAG_STAT_PSH_RES_DELTA("TCP Flag Stat Psh (response)", "tcpFlagStatPshResDelta", 468),
    TCP_FLAG_STAT_ACK_REQ_DELTA("TCP Flag Stat ACK (request)", "tcpFlagStatAckReqDelta", 469),
    TCP_FLAG_STAT_ACK_RES_DELTA("TCP Flag Stat ACK (response)", "tcpFlagStatAckResDelta", 470),
    TCP_FLAG_STAT_URG_REQ_DELTA("TCP Flag Stat Urg (request)", "tcpFlagStatUrgReqDelta", 471),
    TCP_FLAG_STAT_URG_RES_DELTA("TCP Flag Stat Urg (response)", "tcpFlagStatUrgResDelta", 472),
    REQ_CONN_REFUSED("Connect Refused (request)", "reqConnRefused", 473),
    RES_CONN_REFUSED("Connect Refused (response)", "resConnRefused", 474),
    SYN_TIMEOUT("SYN Timeout", "synTimeout", 475),
    SYN_ACK_TIMEOUT("SYN ACK Timeout", "synackTimeout", 476),
    REQ_ACK_TIMEOUT_CNT("ACK Timeout Count (request)", "reqAckTimeoutCnt", 477),
    RES_ACK_TIMEOUT_CNT("ACK Timeout Count (response)", "resAckTimeoutCnt", 478),
    SESSION_TIMEOUT("Session Timeout", "sessionTimeout", 479),
    FIN_WAIT_TIMEOUT("Fin Wait Timeout", "finWaitTimeout", 480),
    CLOSE_WAIT_TIMEOUT("Close Wait Timeout", "closeWaitTimeout", 481),
    LAST_ACK_TIMEOUT("Last ACK Timeout", "lastAckTimeout", 482),

    FRAG_PKTS_TOT_REQ("Fragmented Packets Total (request)", "fragPktsTotReq", 483),
    FRAG_PKTS_TOT_RES("Fragmented Packets Total (response)", "fragPktsTotRes", 484),
    FRAG_PKTS_PER_SEC_REQ("Fragmented Packets Per Sec (request)", "fragPktsPerSecReq", 485),
    FRAG_PKTS_PER_SEC_RES("Fragmented Packets Per Sec (response)", "fragPktsPerSecRes", 486),
    FRAG_PKTS_DELTA_REQ("Fragmented Packets Delta (request)", "fragPktsDeltaReq", 487),
    FRAG_PKTS_DELTA_RES("Fragmented Packets Delta (response)", "fragPktsDeltaRes", 488),
    TTL_MIN_REQ("TTL Min (request)", "ttlMinReq", 489),
    TTL_MIN_RES("TTL Min (response)", "ttlMinRes", 490),
    TTL_MAX_REQ("TTL Max (request)", "ttlMaxReq", 491),
    TTL_MAX_RES("TTL Max (response)", "ttlMaxRes", 492),
    TTL_STAT_1_REQ_TOT("TTL Stat 1 (request)", "ttlStat1ReqTot", 493),
    TTL_STAT_2_REQ_TOT("TTL Stat 2 To 5 (request)", "ttlStat2To5ReqTot", 494),
    TTL_STAT_6_TO_32_REQ_TOT("TTL Stat 6 To 32 (request)", "ttlStat6To32ReqTot", 495),
    TTL_STAT_33_TO_64_REQ_TOT("TTL Stat 33 To 64 (request)", "ttlStat33To64ReqTot", 496),
    TTL_STAT_65_TO_96_REQ_TOT("TTL Stat 65 To 96 (request)", "ttlStat65To96ReqTot", 497),
    TTL_STAT_97_TO_128_REQ_TOT("TTL Stat 97 To 128 (request)", "ttlStat97To128ReqTot", 498),
    TTL_STAT_129_TO_160_REQ_TOT("TTL Stat 129 To 160 (request)", "ttlStat129To160ReqTot", 499),
    TTL_STAT_161_TO_192_REQ_TOT("TTL Stat 161 To 192 (request)", "ttlStat161To192ReqTot", 500),
    TTL_STAT_193_TO_224_REQ_TOT("TTL Stat 193 To 224 (request)", "ttlStat193To224ReqTot", 501),
    TTL_STAT_225_TO_255_REQ_TOT("TTL Stat 225 To 255 (request)", "ttlStat225To255ReqTot", 502),
    TTL_STAT_1_RES_TOT("TTL Stat 1 (response)", "ttlStat1ResTot", 503),
    TTL_STAT_2_TO_RES_TOT("TTL Stat 2 To 5 (response)", "ttlStat2To5ResTot", 504),
    TTL_STAT_6_TO_RES_TOT("TTL Stat 6 To 32 (response)", "ttlStat6To32ResTot", 505),
    TTL_STAT_33_TO_64_RES_TOT("TTL Stat 33 To 64 (response)", "ttlStat33To64ResTot", 506),
    TTL_STAT_65_TO_96_RES_TOT("TTL Stat 65 To 96 (response)", "ttlStat65To96ResTot", 507),
    TTL_STAT_97_TO_128_RES_TOT("TTL Stat 97 To 128 (response)", "ttlStat97To128ResTot", 508),
    TTL_STAT_129_TO_160_RES_TOT("TTL Stat 129 To 160 (response)", "ttlStat129To160ResTot", 509),
    TTL_STAT_161_TO_192_RES_TOT("TTL Stat 161 To 192 (response)", "ttlStat161To192ResTot", 510),
    TTL_STAT_193_TO_224_RES_TOT("TTL Stat 193 To 224 (response)", "ttlStat193To224ResTot", 511),
    TTL_STAT_225_TO_255_RES_TOT("TTL Stat 225 To 255 (response)", "ttlStat225To255ResTot", 512),
    TTL_STAT_1_REQ_PER_SEC("TTL Stat 1 (request)", "ttlStat1ReqPerSec", 513),
    TTL_STAT_2_TO_5_REQ_PER_SEC("TTL Stat 2 To 5 (request)", "ttlStat2To5ReqPerSec", 514),
    TTL_STAT_6_TO_32_REQ_PER_SEC("TTL Stat 6 To 32 (request)", "ttlStat6To32ReqPerSec", 515),
    TTL_STAT_33_TO_64_REQ_PER_SEC("TTL Stat 33 To 64 (request)", "ttlStat33To64ReqPerSec", 516),
    TTL_STAT_65_TO_96_REQ_PER_SEC("TTL Stat 65 To 96 (request)", "ttlStat65To96ReqPerSec", 517),
    TTL_STAT_97_TO_128_REQ_PER_SEC("TTL Stat 97 To 128 (request)", "ttlStat97To128ReqPerSec", 518),
    TTL_STAT_129_TO_160_REQ_PER_SEC("TTL Stat 129 To 160 (request)", "ttlStat129To160ReqPerSec", 519),
    TTL_STAT_161_TO_192_REQ_PER_SEC("TTL Stat 161 To 192 (request)", "ttlStat161To192ReqPerSec", 520),
    TTL_STAT_193_TO_224_REQ_PER_SEC("TTL Stat 193 To 224 (request)", "ttlStat193To224ReqPerSec", 521),
    TTL_STAT_225_TO_255_REQ_PER_SEC("TTL Stat 225 To 255 (request)", "ttlStat225To255ReqPerSec", 522),
    TTL_STAT_1_RES_PER_SEC("TTL Stat 1 (response)", "ttlStat1ResPerSec", 523),
    TTL_STAT_2_TO_5_RES_PER_SEC("TTL Stat 2 To 5 (response)", "ttlStat2To5ResPerSec", 524),
    TTL_STAT_6_TO_32_RES_PER_SEC("TTL Stat 6 To 32 (response)", "ttlStat6To32ResPerSec", 525),
    TTL_STAT_33_TO_64_RES_PER_SEC("TTL Stat 33 To 64 (response)", "ttlStat33To64ResPerSec", 526),
    TTL_STAT_65_TO_96_RES_PER_SEC("TTL Stat 65 To 96 (response)", "ttlStat65To96ResPerSec", 527),
    TTL_STAT_97_TO_128_RES_PER_SEC("TTL Stat 97 To 128 (response)", "ttlStat97To128ResPerSec", 528),
    TTL_STAT_129_TO_160_RES_PER_SEC("TTL Stat 129 To 160 (response)", "ttlStat129To160ResPerSec", 529),
    TTL_STAT_161_TO_192_RES_PER_SEC("TTL Stat 161 To 192 (response)", "ttlStat161To192ResPerSec", 530),
    TTL_STAT_193_TO_224_RES_PER_SEC("TTL Stat 193 To 224 (response)", "ttlStat193To224ResPerSec", 531),
    TTL_STAT_225_TO_255_RES_PER_SEC("TTL Stat 225 To 255 (response)", "ttlStat225To255ResPerSec", 532),
    TTL_STAT_1_REQ_DELTA("TTL Stat 1 (request)", "ttlStat1ReqDelta", 533),
    TTL_STAT_2_TO_5_REQ_DELTA("TTL Stat 2 To 5 (request)", "ttlStat2To5ReqDelta", 534),
    TTL_STAT_6_TO_32_REQ_DELTA("TTL Stat 6 To 32 (request)", "ttlStat6To32ReqDelta", 535),
    TTL_STAT_33_TO_64_REQ_DELTA("TTL Stat 33 To 64 (request)", "ttlStat33To64ReqDelta", 536),
    TTL_STAT_65_TO_96_REQ_DELTA("TTL Stat 65 To 96 (request)", "ttlStat65To96ReqDelta", 537),
    TTL_STAT_97_TO_128_REQ_DELTA("TTL Stat 97 To 128 (request)", "ttlStat97To128ReqDelta", 538),
    TTL_STAT_129_TO_160_REQ_DELTA("TTL Stat 129 To 160 (request)", "ttlStat129To160ReqDelta", 539),
    TTL_STAT_161_TO_192_REQ_DELTA("TTL Stat 161 To 192 (request)", "ttlStat161To192ReqDelta", 540),
    TTL_STAT_193_TO_224_REQ_DELTA("TTL Stat 193 To 224 (request)", "ttlStat193To224ReqDelta", 541),
    TTL_STAT_225_TO_255_REQ_DELTA("TTL Stat 225 To 255 (request)", "ttlStat225To255ReqDelta", 542),
    TTL_STAT_1_RES_DELTA("TTL Stat 1 (response)", "ttlStat1ResDelta", 543),
    TTL_STAT_2_TO_5_RES_DELTA("TTL Stat 2 To 5 (response)", "ttlStat2To5ResDelta", 544),
    TTL_STAT_6_TO_32_RES_DELTA("TTL Stat 6 To 32 (response)", "ttlStat6To32ResDelta", 545),
    TTL_STAT_33_TO_64_RES_DELTA("TTL Stat 33 To 64 (response)", "ttlStat33To64ResDelta", 546),
    TTL_STAT_65_TO_96_RES_DELTA("TTL Stat 65 To 96 (response)", "ttlStat65To96ResDelta", 547),
    TTL_STAT_97_TO_128_RES_DELTA("TTL Stat 97 To 128 (response)", "ttlStat97To128ResDelta", 548),
    TTL_STAT_129_TO_160_RES_DELTA("TTL Stat 129 To 160 (response)", "ttlStat129To160ResDelta", 549),
    TTL_STAT_161_TO_192_RES_DELTA("TTL Stat 161 To 192 (response)", "ttlStat161To192ResDelta", 550),
    TTL_STAT_193_TO_224_RES_DELTA("TTL Stat 193 To 224 (response)", "ttlStat193To224ResDelta", 551),
    TTL_STAT_225_TO_255_RES_DELTA("TTL Stat 225 To 255 (response)", "ttlStat225To255ResDelta", 552),

    LEN_REQ_TOT("Length Total (request)", "lenReqTot", 553),
    LEN_RES_TOT("Length Total (response)", "lenResTot", 554),
    LEN_REQ_PER_SEC("Length Per Sec (request)", "lenReqPerSec", 555),
    LEN_RES_PER_SEC("Length Per Sec (response)", "lenResPerSec", 556),
    LEN_REQ_DELTA("Length Delta (request)", "lenReqDelta", 557),
    LEN_RES_DELTA("Length Delta (response)", "lenResDelta", 558),
    PKTS_REQ_TOT("Packets Total (request)", "pktsReqTot", 559),
    PKTS_RES_TOT("Packets Total (response)", "pktsResTot", 560),
    PKTS_REQ_PER_SEC("Packets Per Sec (request)", "pktsReqPerSec", 561),
    PKTS_RES_PER_SEC("Packets Per Sec (response)", "pktsResPerSec", 562),
    PKTS_REQ_DELTA("Packets Delta (request)", "pktsReqDelta", 563),
    PKTS_RES_DELTA("Packets Delta (response)", "pktsResDelta", 564),
    PKT_LEN_MIN_REQ("Packet Length Min (request)", "pktLenMinReq", 565),
    PKT_LEN_MIN_RES("Packet Length Min (response)", "pktLenMinRes", 566),
    PKT_LEN_MAX_REQ("Packet Length Max (request)", "pktLenMaxReq", 567),
    PKT_LEN_MAX_RES("Packet Length Max (response)", "pktLenMaxRes", 568),
    PKT_LEN_STAT_1_TO_128_REQ_TOT("Packet Length Stat 1 To 128 (request)", "pktLenStat1To128ReqTot", 569),
    PKT_LEN_STAT_129_TO_256_REQ_TOT("Packet Length Stat 129 To 256 (request)", "pktLenStat129To256ReqTot", 570),
    PKT_LEN_STAT_257_TO_512_REQ_TOT("Packet Length Stat 257 To 512 (request)", "pktLenStat257To512ReqTot", 571),
    PKT_LEN_STAT_513_TO_1024_REQ_TOT("Packet Length Stat 513 To 1024 (request)", "pktLenStat513To1024ReqTot", 572),
    PKT_LEN_STAT_1025_TO_1514_REQ_TOT("Packet Length Stat 1025 To 1514 (request)", "pktLenStat1025To1514ReqTot", 573),
    PKT_LEN_STAT_JUMBO_REQ_TOT("Packet Length Stat Jumbo (request)", "pktLenStatJumboReqTot", 574),
    PKT_LEN_STAT_1_TO_128_RES_TOT("Packet Length Stat 1 To 128 (response)", "pktLenStat1To128ResTot", 575),
    PKT_LEN_STAT_129_TO_256_RES_TOT("Packet Length Stat 129 To 256 (response)", "pktLenStat129To256ResTot", 576),
    PKT_LEN_STAT_257_TO_512_RES_TOT("Packet Length Stat 257 To 512 (response)", "pktLenStat257To512ResTot", 577),
    PKT_LEN_STAT_513_TO_1024_RES_TOT("Packet Length Stat 513 To 1024 (response)", "pktLenStat513To1024ResTot", 578),
    PKT_LEN_STAT_1025_TO_1514_RES_TOT("Packet Length Stat 1025 To 1514 (response)", "pktLenStat1025To1514ResTot", 579),
    PKT_LEN_STAT_JUMBO_RES_TOT("Packet Length Stat Jumbo (response)", "pktLenStatJumboResTot", 580),
    PKT_LEN_STAT_1_TO_128_REQ_PER_SEC("Packet Length Stat 1 To 128 (request)", "pktLenStat1To128ReqPerSec", 581),
    PKT_LEN_STAT_129_TO_256_REQ_PER_SEC("Packet Length Stat 129 To 256 (request)", "pktLenStat129To256ReqPerSec", 582),
    PKT_LEN_STAT_257_TO_512_REQ_PER_SEQ("Packet Length Stat 257 To 512 (request)", "pktLenStat257To512ReqPerSec", 583),
    PKT_LEN_STAT_513_TO_1024_REQ_PER_SEC("Packet Length Stat 513 To 1024 (request)", "pktLenStat513To1024ReqPerSec", 584),
    PKT_LEN_STAT_1025_TO_1514_REG_PER_SEC("Packet Length Stat 1025 To 1514 (request)", "pktLenStat1025To1514ReqPerSec", 585),
    PKT_LEN_STAT_JUMBO_REQ_PER_SEC("Packet Length Stat Jumbo (request)", "pktLenStatJumboReqPerSec", 586),
    PKT_LEN_STAT_1_TO_128_RES_PER_SEC("Packet Length Stat 1 To 128 (response)", "pktLenStat1To128ResPerSec", 587),
    PKT_LEN_STAT_129_TO_256_RES_PER_SEC("Packet Length Stat 129 To 256 (response)", "pktLenStat129To256ResPerSec", 588),
    PKT_LEN_STAT_257_TO_512_RES_PER_SEC("Packet Length Stat 257 To 512 (response)", "pktLenStat257To512ResPerSec", 589),
    PKT_LEN_STAT_513_TO_1024_RES_PER_SEC("Packet Length Stat 513 To 1024 (response)", "pktLenStat513To1024ResPerSec", 590),
    PKT_LEN_STAT_1025_TO_1514_RES_PER_SEC("Packet Length Stat 1025 To 1514 (response)", "pktLenStat1025To1514ResPerSec", 591),
    PKT_LEN_STAT_JUMBO_RES_PER_SEC("Packet Length Stat Jumbo (response)", "pktLenStatJumboResPerSec", 592),
    PKT_LEN_STAT_1_TO_128_REG_DELTA("Packet Length Stat 1 To 128 (request)", "pktLenStat1To128ReqDelta", 593),
    PKT_LEN_STAT_129_TO_256_REQ_DELTA("Packet Length Stat 129 To 256 (request)", "pktLenStat129To256ReqDelta", 594),
    PKT_LEN_STAT_257_TO_512_REQ_DELTA("Packet Length Stat 257 To 512 (request)", "pktLenStat257To512ReqDelta", 595),
    PKT_LEN_STAT_513_TO_1024_REQ_DELTA("Packet Length Stat 513 To 1024 (request)", "pktLenStat513To1024ReqDelta", 596),
    PKY_LRN_STAT_1025_TO_1514_REG_DELTA("Packet Length Stat 1025 To 1514 (request)", "pktLenStat1025To1514ReqDelta", 597),
    PKT_LEN_STAT_JUMBO_REQ_DELTA("Packet Length Stat Jumbo (request)", "pktLenStatJumboReqDelta", 598),
    PKT_LEN_STAT_1_TO_128_RES_DELTA("Packet Length Stat 1 To 128 (response)", "pktLenStat1To128ResDelta", 599),
    PKT_LEN_STAT_129_TO_256_RES_DELTA("Packet Length Stat 129 To 256 (response)", "pktLenStat129To256ResDelta", 600),
    PKT_LEN_STAT_257_TO_512_RES_DELTA("Packet Length Stat 257 To 512 (response)", "pktLenStat257To512ResDelta", 601),
    PKT_LEN_STAT_513_TO_1024_RES_DELTA("Packet Length Stat 513 To 1024 (response)", "pktLenStat513To1024ResDelta", 602),
    PKT_LEN_STAT_1025_TO_1514_RES_DELTA("Packet Length Stat 1025 To 1514 (response)", "pktLenStat1025To1514ResDelta", 603),
    PKT_LEN_STAT_JUMBO_RES_DELTA("Packet Length Stat Jumbo (response)", "pktLenStatJumboResDelta", 604);


    private static final Map<Object, AlarmType2Dept> BY_DEPT2_INFO = new HashMap<>();

    static {
        for (AlarmType2Dept e : values()) {
            BY_DEPT2_INFO.put(e.getName(), e);
            BY_DEPT2_INFO.put(e.getCodeName(), e);
            BY_DEPT2_INFO.put(e.getIndexNum(), e);
        }
    }

    public static AlarmType2Dept valueOfName(String name) {
        return BY_DEPT2_INFO.get(name);
    }

    public static AlarmType2Dept valueOfNameCode(String codeName) {
        return BY_DEPT2_INFO.get(codeName);
    }

    public static AlarmType2Dept valueOfIndexNum(Integer indexNum) {
        return BY_DEPT2_INFO.get(indexNum);
    }

    @Getter
    private String name;
    @Getter
    private String codeName;
    @Getter
    private Integer indexNum;

    AlarmType2Dept(String name, String codeName, Integer indexNum) {
        this.name = name;
        this.codeName = codeName;
        this.indexNum = indexNum;
    }
}
